# -*- coding: UTF-8 -*-

# Import from standard library
import os
import proj
import unittest
import pandas as pd

# Import from our lib
from proj.erwan import for_test, clean_data, overlapping, layout


class TestUtils(unittest.TestCase):
    def setUp(self):
        datapath = os.path.dirname(os.path.abspath(proj.__file__)) + '/data'
        df01 = pd.read_csv('{}/20101101.over_player_day.csv'.format(datapath),
                           usecols=[2, 3],
                           header=None)
        df02 = pd.read_csv('{}/20101102.over_player_day.csv'.format(datapath),
                           usecols=[2, 3],
                           header=None)
        self.df01 = df01
        self.df02 = df02
        self.df = df01.append(df02)

    def test_for_test(self):
        res = 'success'
        out = for_test()
        self.assertEqual(res, out)

    def test_clean_data(self):
        res = {'game': {0: 'g_0',
                        1: 'g_0',
                        2: 'g_4',
                        3: 'g_1',
                        4: 'g_2',
                        5: 'g_1',
                        6: 'g_4',
                        7: 'g_3'},
               'player': {0: 'play_1',
                          1: 'play_2',
                          2: 'play_2',
                          3: 'play_3',
                          4: 'play_3',
                          5: 'play_4',
                          6: 'play_5',
                          7: 'play_9'}}
        out = clean_data(self.df)
        self.assertEqual(res, out.to_dict())

    def test_overlapping(self):
        res = {
            'game_x': {0: 'g_0',
                       1: 'g_1',
                       2: 'g_2',
                       3: 'g_3',
                       4: 'g_4',
                       5: 'g_0',
                       6: 'g_1',
                       7: 'g_2',
                       8: 'g_3',
                       9: 'g_4',
                       10: 'g_0',
                       11: 'g_1',
                       12: 'g_2',
                       13: 'g_3',
                       14: 'g_4',
                       15: 'g_0',
                       16: 'g_1',
                       17: 'g_2',
                       18: 'g_3',
                       19: 'g_4',
                       20: 'g_0',
                       21: 'g_1',
                       22: 'g_2',
                       23: 'g_3',
                       24: 'g_4'},
            'game_y': {0: 'g_0',
                       1: 'g_0',
                       2: 'g_0',
                       3: 'g_0',
                       4: 'g_0',
                       5: 'g_1',
                       6: 'g_1',
                       7: 'g_1',
                       8: 'g_1',
                       9: 'g_1',
                       10: 'g_2',
                       11: 'g_2',
                       12: 'g_2',
                       13: 'g_2',
                       14: 'g_2',
                       15: 'g_3',
                       16: 'g_3',
                       17: 'g_3',
                       18: 'g_3',
                       19: 'g_3',
                       20: 'g_4',
                       21: 'g_4',
                       22: 'g_4',
                       23: 'g_4',
                       24: 'g_4'},
            'tot_x': {0: 2,
                      1: 2,
                      2: 2,
                      3: 1,
                      4: 1,
                      5: 2,
                      6: 2,
                      7: 2,
                      8: 1,
                      9: 1,
                      10: 2,
                      11: 2,
                      12: 2,
                      13: 1,
                      14: 1,
                      15: 2,
                      16: 2,
                      17: 2,
                      18: 1,
                      19: 1,
                      20: 2,
                      21: 2,
                      22: 2,
                      23: 1,
                      24: 1},
            'tot_x_y': {0: 2,
                        1: 0,
                        2: 0,
                        3: 0,
                        4: 1,
                        5: 0,
                        6: 2,
                        7: 1,
                        8: 0,
                        9: 0,
                        10: 0,
                        11: 1,
                        12: 1,
                        13: 0,
                        14: 0,
                        15: 0,
                        16: 0,
                        17: 0,
                        18: 1,
                        19: 0,
                        20: 1,
                        21: 0,
                        22: 0,
                        23: 0,
                        24: 2}
        }
        df = pd.DataFrame({'game': {0: 'g_0',
                                    1: 'g_0',
                                    2: 'g_4',
                                    3: 'g_1',
                                    4: 'g_2',
                                    5: 'g_1',
                                    6: 'g_4',
                                    7: 'g_3'},
                           'player': {0: 'play_1',
                                      1: 'play_2',
                                      2: 'play_2',
                                      3: 'play_3',
                                      4: 'play_3',
                                      5: 'play_4',
                                      6: 'play_5',
                                      7: 'play_9'}})
        out = overlapping(df)
        self.maxDiff = None
        self.assertEqual(res, out.to_dict())

    def test_layout(self):
        res = {
            'game_x': {0: 'g_0',
                       1: 'g_0',
                       2: 'g_1',
                       3: 'g_1',
                       4: 'g_1',
                       5: 'g_2',
                       6: 'g_4',
                       7: 'g_4'},
            'game_y': {0: 'g_1',
                       1: 'g_4',
                       2: 'g_0',
                       3: 'g_2',
                       4: 'g_4',
                       5: 'g_1',
                       6: 'g_0',
                       7: 'g_1'},
            'overlapping': {0: 33.333333333333336,
                            1: 33.333333333333336,
                            2: 50.0,
                            3: 50.0,
                            4: 50.0,
                            5: 50.0,
                            6: 100.0,
                            7: 100.0},
            'tot_x': {0: 3,
                      1: 3,
                      2: 2,
                      3: 2,
                      4: 2,
                      5: 2,
                      6: 1,
                      7: 1},
            'tot_x_y': {0: 1,
                        1: 1,
                        2: 1,
                        3: 1,
                        4: 1,
                        5: 1,
                        6: 1,
                        7: 1}
        }

        df = pd.DataFrame({
            'game_x': {0: 'g_0',
                       1: 'g_1',
                       2: 'g_2',
                       3: 'g_3',
                       4: 'g_4',
                       5: 'g_0',
                       6: 'g_1',
                       7: 'g_2',
                       8: 'g_3',
                       9: 'g_4',
                       10: 'g_0',
                       11: 'g_1',
                       12: 'g_2',
                       13: 'g_3',
                       14: 'g_4',
                       15: 'g_0',
                       16: 'g_1',
                       17: 'g_2',
                       18: 'g_3',
                       19: 'g_4',
                       20: 'g_0',
                       21: 'g_1',
                       22: 'g_2',
                       23: 'g_3',
                       24: 'g_4'},
            'game_y': {0: 'g_0',
                       1: 'g_0',
                       2: 'g_0',
                       3: 'g_0',
                       4: 'g_0',
                       5: 'g_1',
                       6: 'g_1',
                       7: 'g_1',
                       8: 'g_1',
                       9: 'g_1',
                       10: 'g_2',
                       11: 'g_2',
                       12: 'g_2',
                       13: 'g_2',
                       14: 'g_2',
                       15: 'g_3',
                       16: 'g_3',
                       17: 'g_3',
                       18: 'g_3',
                       19: 'g_3',
                       20: 'g_4',
                       21: 'g_4',
                       22: 'g_4',
                       23: 'g_4',
                       24: 'g_4'},
            'tot_x': {0: 3,
                      1: 2,
                      2: 2,
                      3: 1,
                      4: 1,
                      5: 3,
                      6: 2,
                      7: 2,
                      8: 1,
                      9: 1,
                      10: 3,
                      11: 2,
                      12: 2,
                      13: 1,
                      14: 1,
                      15: 3,
                      16: 2,
                      17: 2,
                      18: 1,
                      19: 1,
                      20: 3,
                      21: 2,
                      22: 2,
                      23: 1,
                      24: 1},
            'tot_x_y': {0: 2,
                        1: 1,
                        2: 0,
                        3: 0,
                        4: 1,
                        5: 1,
                        6: 3,
                        7: 1,
                        8: 0,
                        9: 1,
                        10: 0,
                        11: 1,
                        12: 1,
                        13: 0,
                        14: 0,
                        15: 0,
                        16: 0,
                        17: 0,
                        18: 1,
                        19: 0,
                        20: 1,
                        21: 1,
                        22: 0,
                        23: 0,
                        24: 2}
        })
        out = layout(df)
        self.assertEqual(res, out.to_dict())


if __name__ == '__main__':
    unittest.main()
